{
    'name': 'progress_project_enet',
    'version': '1.0.0',
    'category': 'field',
    'description': """
        this is progress project field for enet department
        """,
    'author': 'prakon wiriyatanavirod',
    'website': 'www.kmutnb.ac.th',
    'depends': ['base','email_template',],
    'demo': [],
    'data': ['views/menu_progress.xml',
             'views/input_subject_view.xml',
             'views/input_teacher_view.xml',
             'views/input_student_view.xml',
             'views/data_project_view.xml',
             'report/call_report.xml',
             'views/project_summary_view.xml',
             'views/score_summary_view.xml',
             'views/auto_job.xml',
             'views/progress_exams.xml',
             'views/protect_exams.xml',
             'wizards/progress_exams_views.xml',
             'wizards/protect_exams_views.xml',
             'security/ir.model.access.csv',
             'views/ir_cron.xml',
             'datas/email_temp.xml',
             'views/act_email_temp.xml',
             'views/ir_mail_server.xml',
             ],
    'update_xml': [],
    'installable': True,
    'auto_install': False,
    'application': True,
}
